# Generated by Django 3.1.7 on 2021-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('completed', '-id')},
        ),
    ]
